### ISSUE TITLE
next rmarkdown release breaks some tests 

### ISSUE THREAD

**Issue by cderv** [ThinkR-open/gitdown#17]
We are about to release **rmarkdown** 2.12 and our check of reverse dependencies show an issue with `test-git_down.R`

From `testthat.Rout.fail`
```r
[ FAIL 6 | WARN 0 | SKIP 0 | PASS 73 ]

══ Failed tests ════════════════════════════════════════════════════════════════
── Failure (test-git_down.R:25:5): git_down function ───────────────────────────
`one_line_exists` has length 0, not length 1.
── Failure (test-git_down.R:26:5): git_down function ───────────────────────────
`sub_commit_1` has length 0, not length 1.
── Failure (test-git_down.R:27:5): git_down function ───────────────────────────
`sub_commit_2` has length 0, not length 1.
── Failure (test-git_down.R:48:5): git_down no name function ───────────────────
length(one_line_exists) == 1 is not TRUE

`actual`:   FALSE
`expected`: TRUE 
── Failure (test-git_down.R:75:5): git_down multiple pattern works ─────────────
length(one_line_ticket_exists) == 1 is not TRUE

`actual`:   FALSE
`expected`: TRUE 
── Failure (test-git_down.R:80:5): git_down multiple pattern works ─────────────
length(one_line_exists) == 1 is not TRUE

`actual`:   FALSE
`expected`: TRUE 

[ FAIL 6 | WARN 0 | SKIP 0 | PASS 73 ]
Error: Test failures
Execution halted
```

**rmarkdown** 2.12 has a new way to insert the anchor section using a Lua filter and not only a JS script. This is why the HTML code has changed. Some of the test are failing because of that. There could be other reasons too. 

In general, testing the HTML code is not robust, especially using fixed string. Better ways, are regex or **xml2**. 
Probably using regex here would solve the issue. 

Also the output of **rmarkdown** can be quite different in HTML file depending on the Pandoc version. We're still unsure which version CRAN is using but if they change it somehow it could also break  some test doing matching. Also, when running your test, I am not sure to know which version to use. Skipping on CRAN test that run pandoc could also be the way to go. if you run tests in CI too, you are covered (but not by our rev dep check)

Anyway, the tests should be updated and a patch release pushed on CRAN otherwise when we'll make the release, **gitdown** will have some failure.

Thanks !

**Comment by cderv** [comment]
Example of differences: 
* `<h2><span class=\"header-section-number\">1.2</span> Issue: #1</h2>`
* `<h2><span class=\"header-section-number\">1.2</span> Issue: #1<a href=\"section-issue.html#issue-1\" class=\"anchor-section\" aria-label=\"Anchor link to header\"></a></h2>`

**Comment by statnmap** [comment]
Thank you.

This PR uses regex for the unit tests: https://github.com/ThinkR-open/gitdown/pull/18
It seems to be good in the CI that uses the last version of {rmarkdown}.  
I will soon submit this new version to CRAN.
